### PR TITLE
Fixes for Vrui-4 enabling HTC Vive

### PR DESCRIPTION
**Pull request by bilke**
- Fixed menus
- Fixed Vive rendering

Related: https://github.com/VruiVTK/vtkVRUI-superbuild/pull/2

In principal the VolumeViewer works but volume rendering looks a little bit odd:

It looks like the view direction is not passed to the volume rendering shader. So seen from the top it looks good but when diving in to the dataset one can see that the rendering happens on a surface which is always pointing upwards and not adapting to the viewing direction. It is hard to describe.. Also the volume rendering disappears completely when viewing from specific angles..

### CODE REVIEW

**Comment by sankhesh** [comment]
@bilke Thank you for the contribution. Looks good.
***Question*** Does this break backwards compatibility with previous Vrui releases?

> It looks like the view direction is not passed to the volume rendering shader. So seen from the top it looks good but when diving in to the dataset one can see that the rendering happens on a surface which is always pointing upwards and not adapting to the viewing direction. It is hard to describe.. Also the volume rendering disappears completely when viewing from specific angles..

We pass the modelview matrix to the volume rendering shader and it should be updated every frame. 
Which backend do you use for VTK - OpenGL or OpenGL2?

I've not tried this using Vrui with the Vive, but it works well on 3D displays including a CAVE and IQStation.
Have you tried the [GeometryViewer](https://github.com/VruiVTK/GeometryViewer) example?

**Comment by sankhesh** [comment]
Just spoke to Aashish about this. 

One thing you can try is looking at whether VTK gets the right matrix from OpenGL and see if they are updated every frame. You can add print statements to the [vtkExternalOpenGLRenderer.cxx::Render()](https://github.com/Kitware/VTK/blob/d38a3e76f9101d82266107436647c471d6547972/Rendering/External/vtkExternalOpenGLRenderer.cxx#L57-L88) for the modelview matrix, camera position, focal point, etc.

The [shader code](https://github.com/Kitware/VTK/blob/d38a3e76f9101d82266107436647c471d6547972/Rendering/VolumeOpenGL2/vtkVolumeShaderComposer.h#L319-L329) in the OpenGL2 volume mapper computes the ray direction based on the camera position. Ensuring that the camera position is updated correctly would definitely help.

**Comment by bilke** [comment]
@sankhesh and @aashish24 Thanks for your reply! 

- Backwards compatibility: TODO!
- OpenGL-backend: `OpenGL2`
- Trying out geometryviewer: TODO!

Regarding the volume rendering issues:

- All regular VTK rendering (e.g. Slices and Contours from the Widgets) is fine
- I added some debug output as you suggested -> cam position, up-vector and focal point seem to be fine and are updated every frame
- Every frame I get an OpenGL error: `glPrintError: Invalid operation`
- I noticed the line `double position[4] = {0.0, 0.0, 1.0, 1.0}, newPosition[4];` in [vtkExternalOpenGLRenderer.cxx#L78](https://github.com/Kitware/VTK/blob/d38a3e76f9101d82266107436647c471d6547972/Rendering/External/vtkExternalOpenGLRenderer.cxx#L78). Why is there a `1.0` in the third component? I changed it to `0.0` -> `double position[4] = {0.0, 0.0, 0.0, 1.0}, newPosition[4];` and the issues seem to be gone! Although cam position and focal point now have the same value!? What do you think about this!

**Comment by aashish24** [comment]
> {0.0, 0.0, 1.0, 1.0}, newPosition[4];

The third component should be 0.0 when calculating the position of the camera since the default should be at 0.0, 0.0, 0.0. I think we had 1.0 because by default we assumed that camera was at distance 1 unit away from Z and looking at the origin. However, it should be that, camera should be placed at 0.0, 0.0, 0.0. The focalpoint should be 0.0, 0.0, -1.0.

**Comment by aashish24** [comment]
I think we copied the defaults from here: https://github.com/Kitware/VTK/blob/master/Rendering/Core/vtkCamera.cxx

**Comment by sankhesh** [comment]
> I noticed the line double position[4] = {0.0, 0.0, 1.0, 1.0}, newPosition[4]; in vtkExternalOpenGLRenderer.cxx#L78. Why is there a 1.0 in the third component?

Good eye @bilke. As @aashish24 suggested, that seems like a bug.

The issue might have always been there but not noticeable in large CAVE displays.

Mind creating a [merge request to VTK](https://gitlab.kitware.com/vtk/vtk/blob/master/CONTRIBUTING.md)?

**Comment by bilke** [comment]
@sankhesh @aashish24 
I tested with the corrected focal point too and it seems to work fine.

As a long-time VTK user it would be an honor to create a merge request! 😃 

One more question regarding volume rendering: when diving into the data set (with my head) the clipping hides the whole data set. Can clipping somehow be disabled?

**Comment by aashish24** [comment]
> One more question regarding volume rendering: when diving into the data set (with my head) the clipping hides the whole data set. Can clipping somehow be disabled?

it seems to me that somehow VTK Volume mapper does not correctly knows the camera parameters which triggers the clipping. We will need to clipped geometry to correctly render the volume. @sankhesh can you look into the CameraIsInside code and see what might be wrong?

@bilke what version of VTK are you using?

**Comment by bilke** [comment]
@aashish24 I am using the [superbuild which uses the current master branch of VTK](https://github.com/VruiVTK/vtkVRUI-superbuild/blob/master/versions.cmake#L21-L24).

**Comment by bilke** [comment]
Here is the [merge request](https://gitlab.kitware.com/vtk/vtk/merge_requests/2814)

**Comment by bilke** [comment]
@sankhesh Thanks for merging the VTK request!

I tried out backwards compatibility with Vrui 3.1 and unfortunately the changes required for the menus are not compatible (`PopupMenu` has no member `manageMenu()`). I can add compatibility with 3.1 by introducing `#if`s in the source code. Please tell me if I should do it. Beside that and the volume rendering clipping issue all is fine!

**Comment by sankhesh** [comment]
@bilke Thank you for looking into it.

I think it would be okay to support Vrui 4 only. If someone has a strong requirement to support Vrui 3.x, we can add `#if`s then.

I'll create a new issue for clipping and merge this PR. Thank you again, for the contribution :+1:

**Comment by bilke** [comment]
@sankhesh Thanks for your help and merging!

**Pull request merged**
